### ISSUE TITLE
[MacOS]: Indentation is changed when typing begins

### ISSUE THREAD

**Issue by jmitchem** [VsVim/VsVim#2895]
**Describe the bug**
When editing C# in MacOS Visual Studio, starting a new line with 'o', or within insert mode places the caret correctly.  However when any other typing begins, it shifts everything to the left by 1 tab unit.

This is an out of the box VS for Mac install and VsVim install.  No configuration changes to either.

![Screen Recording 2021-05-13 at 12 27 06 PM](https://user-images.githubusercontent.com/18061729/118177347-6cda5f80-b3e7-11eb-8b6f-05479a384c01.gif)

**Environment (please complete the following information):**

- Visual Studio version:  Visual Studio for Mac 8.9.9 (build 3)
- VsVim version: 2.8.0.11
- Programming Language: C#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Comment by nosami** [comment]
Strange, I haven't seen that happen before.

There are some known bugs with the latest release though that are fixed in this build https://dev.azure.com/VsVim/503f82b4-a499-4dec-abba-84bfda309969/_apis/build/builds/555/artifacts?artifactName=VSMacExtension&api-version=6.0&%24format=zip

Please could you try this version via `Visual Studio -> Extensions -> Install from file` and browse to the .mpack file contained in the zip?

**Comment by jmitchem** [comment]
Thank you, yes, this works great.

**Comment by khalylk** [comment]
I am having the same exact issue described above 
Visual Studio for MAC 8.9.10 (build 4)
VsVim version: 2.8.0.11
Programming Language: C#

The link posted above (build 555) no longer exists.  
I tried to install the latest build version I found but the issue is not fixed.
https://dev.azure.com/VsVim/503f82b4-a499-4dec-abba-84bfda309969/_apis/build/builds/562/artifacts?artifactName=VSMacExtension&api-version=6.0&%24format=zip

**Comment by nosami** [comment]
[Vim.Mac.VsVim_2.8.0.15.mpack.zip](https://github.com/VsVim/VsVim/files/6527004/Vim.Mac.VsVim_2.8.0.15.mpack.zip)
@khalylk try this build - you'll need to unzip it first, then install the mpack file manually

**Comment by khalylk** [comment]
@nosami Thanks Jason!  That seems to do the trick.  fyi, I had to upgrade to 8.10 VS MAC preview

**Comment by nosami** [comment]
> fyi, I had to upgrade to 8.10 VS MAC preview

Oops, sorry about that - I built that mpack on my own machine which is running 8.10. Let me know if you need a version to run on 8.9

**Comment by matthewwen** [comment]
I'm running into the same issue as well. 

Visual Studio for Mac Community: 8.9.10
VsVim: 2.8.0.11
Programming Language: C#

I did a clean install and did little to no modifications to my visual studio, so I'm not sure why it is doing this. I also tried your 2.8.0.15 link, and that didn't work as well.

**Comment by nosami** [comment]
@matthewwen Please can you try uninstalling 2.8.0.15 and installing 2.8.0.12 from the feed within VSMac? Thanks

**Comment by matthewwen** [comment]
Never mind. I switched IDE, so ignore my comment.

**Comment by nosami** [comment]
Closing as this was fixed in 2.8.0.12 and fix has been confirmed.
