### ISSUE TITLE
VsVim for Visual Studio for Mac '$' and backspace doesn't work as expected. 

### ISSUE THREAD

**Issue by jawee** [VsVim/VsVim#3015]
**Describe the bug**
There are probably more "issues", but I have found that default things like using backspace in insert mode, and trying to go to the end of a line with '$' doesn't work as expected.

It seems like VS detects '$' as option + 4, instead of the dollar sign, so when I press this combination, I insert a '$' instead of going to the end of the line. 

Backspace just refuses to work if there's a ';'.
For example the line:
```csharp
var myVariable = "test";
````
if I try to use backspace in insert mode with the cursor on the ';', nothing happens. If I move inside the word "test", it works fine. 
Some research has told me that this is actually the default VI setting, although I have never experienced it before. 

**To Reproduce**
Pressing $ (option + 4) in normal mode, a dollar sign is now inserted at the cursor.

**Expected behavior**
Expect to get to the end of the line

**Environment (please complete the following information):**

- Visual Studio version: 17.3.5 (Visual Studio for Mac)
- VsVim version: 2.8.0.18
- Programming Language:
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**
This might be related to my Swedish keyboard language, although I doubt it.

I have found workarounds by setting the following in my .vsvimrc. So remapping option+4 to $, and set backspace=2 to restore normal backspace functionality.

```
set backspace=2
nnoremap <M-4> $
```

Note:
The following is written about contributing.
https://github.com/VsVim/VsVim/blob/master/CONTRIBUTING.md

General Keyboard configuration problems are described below.
https://github.com/VsVim/VsVim/issues/2527

**Comment by nosami** [comment]
Yeah... the backspace key works the same way in Vim without any vimrc settings to override its behaviour.
This confused me as well when I first saw it and there is another issue being tracked for this. https://github.com/VsVim/VsVim/issues/2920 
I think I need to change the defaults to behave more like VS than Vim.

I'll try and reproduce your `$` issue later. I use a UK keyboard and `$` is entered using `shift 4` not `option 4`. Maybe there are some issues when using different keyboard layouts. I never tested this.

**Comment by nosami** [comment]
I reproduced the issue with `$` on my first attempt. I'll debug this and see what's going wrong.

**Comment by nosami** [comment]
OK. I think this is fixed by #3016. I didn't notice any side effects when using a UK keyboard and I verified that Option+4 works as `$` on a Swedish keyboard layout.

It would be great if you could help test this for me before it gets merged in. (Download https://github.com/VsVim/VsVim/suites/8398435252/artifacts/371149552, extract the mpack file from the zip and then load this into VSMac `Visual Studio -> Extensions -> Install from file`, then select the mpack file and restart.)

**Comment by jawee** [comment]
Works perfect for fixing '$' (yes I removed my "fix" from my vsvimrc). :)

Although I don't think it's a special case for '$', it's something general. '{' just inserts a { (opt+shift+8), '^' just inserts an ^ (shift+¨). Could it be something like vsvim (or VS) detects the key combination pressed, instead of the actual character?

**Comment by nosami** [comment]
Hmm... with this fix in place, when I press opt+shift+8 in Normal mode, it doesn't insert a `{` but moves up by a paragraph like I would expect

**Comment by nosami** [comment]
<img width="599" alt="image" src="https://user-images.githubusercontent.com/667194/191540931-7e885ae2-c0e5-4a40-95f5-2fa6e8dc7478.png">
I just tried the ^ key and that worked for me too. I had to look up the key on the keyboard viewer as ^ is option-shift-} for me :)

**Comment by jawee** [comment]
Took me a second to get back to testing, I can confirm that '{'-jumping now works as I expect. I must have done something wrong before. 

I still have issues with '^' though, https://im5.ezgif.com/tmp/ezgif-5-43904ac547.gif (if the gif gets taken down I'll upload it somewhere)

**Comment by nosami** [comment]
Ah, I see. You are entering `^` using `shift ¨` and I am using `option+shift+¨` (which works)

I must have another bug somewhere. Should be an easy fix.

**Comment by jawee** [comment]
The difference is that shift+¨ requires a space after to input '^', option+shift+¨ enters '^' immediately without requiring pressing space bar afterwards.

**Comment by jawee** [comment]
https://im5.ezgif.com/tmp/ezgif-5-8a79dfd53f.gif made another gif in (neo)vim to show how it works. It might be me that enters ^ in a weird way..

**Comment by nosami** [comment]
It should work no matter how you enter it. I'll fix it one way or another.

Seems like my assumptions about how keyboard input works are flawed :)

**Comment by jawee** [comment]
Or that you've found the one person who inputs ^ in a flawed way :)

**Comment by nosami** [comment]
Are there any other keys that are input in a similar way?

**Comment by jawee** [comment]
The others I can think of are: ¨ ´ ` ~ 
Although I've never used any of them in vim, not sure if they have a function :)

**Comment by nosami** [comment]
Hey @jawee, I've got a newer build and would really appreciate it if you could help me to test it. https://github.com/VsVim/VsVim/suites/8500376704/artifacts/378348774

I think this is working now how it should (except for an annoying beep when switching from Insert mode back to Normal mode)

**Comment by jawee** [comment]
I will test it asap, might have to wait until tomorrow afternoon though. :)

**Comment by nosami** [comment]
> I will test it asap, might have to wait until tomorrow afternoon though. :)

Great, I should have fixed the annoying beep issue by then :)

**Comment by jawee** [comment]
Seems to have fixed the issues I had :)

**Comment by nosami** [comment]
Great news. I'll get this merged and published.
